services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - php-fpm
      - php-myadmin
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    restart: always

  php-fpm:
    container_name: php-fpm
    build:
      context: requirements/php-fpm
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    restart: on-failure


  wordpress-init:
    container_name: wordpress-init
    build:
      context: requirements/wordpress-init
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: "no"

  php-myadmin:
    container_name: php-myadmin
    build:
      context: requirements/php-myadmin
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/data/wordpress
      o: bind

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge
